AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'Gemfile'
    - 'spec/support/**/*'
    - 'app/lib/**/*'
Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
